---
title: "Heliaphen"
output:
  flexdashboard::flex_dashboard:
    source_code: embed
runtime: shiny
---

```{r setup, include=FALSE}
library(lubridate)
library(readr)
library(readxl)
library(tidyverse)
library(broom)
library(modelr)
library(viridis)
library(plotly)
library(scales)
library(flexdashboard)
library(rheliaphen)
library(rsunflo)
library(shiny)

# options
theme_set(theme_bw())
lim_area <- c(0, 350)
scale_treatment <- scale_colour_manual(values = c("control"="#619CFF","stress"="#F8766D"))
list_ftsw <- list(data_frame(FTSW=seq(0,1,0.05)))

```


```{r data_input, include=FALSE}
# experiment parameters
data_trial <- reactive({
  read_excel(paste0("data/heliaphen_experiments.xlsx")) %>% 
    mutate(start=ymd(start, tz="Europe/Paris"), end=ymd(end, tz="Europe/Paris")) %>% 
    filter(experiment==input$experiment)
})

list_experiment <- reactive({
  read_excel(paste0("data/heliaphen_experiments.xlsx")) %>% select(experiment) %>% arrange(experiment) %>% .$experiment
})

# design of experiment
data_index <- reactive({
  read_excel(paste0("data/",input$experiment,"/",input$experiment,"_index.xlsx"))
})

# list of genotypes in selected experiment
list_genotype <- reactive({
  data_index() %>% select(genotype) %>% distinct() %>% arrange(genotype) %>% .$genotype
})

# pot weight
data_weight <- reactive({
  read_rds(paste0("data/",input$experiment,"/",input$experiment,"_weight.rds")) 
})

# leaf area
data_area_raw <- reactive({
  read_rds(paste0("data/",input$experiment,"/",input$experiment,"_area_raw.rds")) 
})

data_area <- reactive({
  read_rds(paste0("data/",input$experiment,"/",input$experiment,"_area.rds")) 
})

```

```{r data_computed_water, include=FALSE}
# compute soil water deficit as a function of pot weight and available water content
data_ftsw <- reactive({
  data_weight() %>%
    soil_water_deficit(
      date_start=data_trial()$start,
      date_end=data_trial()$end,
      weight_dead=data_trial()$weight_dead,
      awc=input$threshold_awc,
      timing="measure"
    ) 
})

# compute interpolated soil water deficit
data_ftsw_daily <- reactive({
  data_weight() %>%
    soil_water_deficit(
      date_start=data_trial()$start,
      date_end=data_trial()$end,
      weight_dead=data_trial()$weight_dead,
      awc=input$threshold_awc,
      timing="daily"
    ) 
})

# compute mean soil water deficit per genotype
data_ftsw_mean <- reactive({
  data_ftsw_daily() %>% 
    group_by(treatment, genotype, time) %>% 
    summarise(FTSW=mean(FTSW), d_weight=mean(d_weight)) 
})

# table for stressed plant below defined water deficit threshold
table_harvest <- reactive({
  data_ftsw() %>%
    plant_harvest(
      date_start=ymd(as.character(input$date[1]), tz="Europe/Paris"),
      date_end=ymd(as.character(input$date[2]), tz="Europe/Paris"),
      threshold=input$threshold_ftsw
    )
})

```

```{r data_computed_plant, include=FALSE}
# compute plant leaf area as the sum of individual leaf area
data_plant <- reactive({
  data_area() %>%
    mutate(area_active=ifelse(senescence==0, area, 0)) %>% 
    group_by(plant_code, time) %>%
    summarise(
      area=sum(area),
      area_active=sum(area_active),
      senescence=sum(senescence)
    ) %>% 
    left_join(data_index())
})

```

```{r data_computed_expansion, include=FALSE}
# compute expansion rate as differences between consecutive dates for all plant_code
data_expansion <- reactive({
  data_plant() %>% 
    group_by(plant_code) %>% 
    mutate(
      d_area= area - lag(area),
      d_area_active= area_active - lag(area_active)
    )
})

data_expansion_mean <- reactive({
  data_expansion() %>%
    group_by(treatment, genotype, time) %>%
    summarise(d_area=mean(d_area))
})

# compute mean relative expansion rate as mean(stress):mean(control)
data_rer_mean <- reactive({
  data_expansion_mean() %>% 
    spread(treatment, d_area) %>% 
    mutate(rer=stress/control)
})

# compute relative expansion rate as stress:mean(control) 
data_rer <- reactive({
  data_expansion() %>% 
    filter(treatment == "stress") %>% 
    select(treatment, genotype, plant_code, time, d_area) %>% 
    spread(treatment, d_area) %>% 
    left_join(data_rer_mean() %>% select(genotype, time, control)) %>% 
    mutate(rer=stress/control)
})

# analyse expansion response as mean(RER)=f(mean(FTSW))
data_response_expansion_mean <- reactive({
  data_rer_mean() %>% 
    left_join(
      data_ftsw_mean() %>% ungroup() %>% 
        filter(treatment=="stress") %>%
        select(genotype, time, FTSW)
    )
})

# analyse expansion response as RER=f(FTSW)
data_response_expansion <- reactive({
  data_rer() %>% 
    left_join(data_ftsw_daily() %>% select(plant_code, time, FTSW))
})

# modeling expansion response : regression on stressed:mean(contron) ~ mean(FTSW)
model_expansion <- function(data) nls(rer ~ curve_expansion(FTSW, a), data=data, start=list(a=-10), algorithm="default")

data_model_expansion <- reactive({
  data_response_expansion() %>% 
  group_by(genotype) %>% 
  nest() %>% 
  mutate(
    model=map(data, failwith(data.frame(NULL), model_expansion)),
    prediction=map2(list_ftsw, model, failwith(data.frame(NULL), add_predictions)),
    coefficients=map(model, failwith(data.frame(NULL), tidy, quiet=TRUE)),
    rmse=map2(model, data, failwith(NULL, rmse))
  )
})


```

```{r data_computed_transpiration, include=FALSE}
# compute plant transpiration rate
data_transpiration <- reactive({
  data_plant() %>% 
    left_join(data_ftsw_daily() %>% select(plant_code, time, d_weight)) %>% 
    group_by(plant_code) %>% 
    mutate(tr=d_weight/area) 
})

# compute mean plant transpiration rate
data_transpiration_mean <- reactive({
  data_transpiration() %>%
    group_by(treatment, genotype, time) %>%
    summarise(d_weight=mean(d_weight), tr=mean(tr))
})

# compute mean relative transpiration rate as mean(stress):mean(control)
data_rtr_mean <- reactive({
  data_transpiration_mean() %>% 
    select(-d_weight) %>% 
    spread(treatment, tr) %>% 
    mutate(rtr=stress/control)
})

# compute relative expansion rate as stress:mean(control)
data_rtr <- reactive({
  data_transpiration() %>% 
    filter(treatment == "stress") %>% 
    select(treatment, genotype, plant_code, time, tr) %>% 
    spread(treatment, tr) %>% 
    left_join(data_rtr_mean() %>% select(genotype, time, control)) %>% 
    mutate(rtr=stress/control)
})

# analyse transpiration response as mean(RER)=f(mean(FTSW))
data_response_transpiration_mean <- reactive({
  data_rtr_mean() %>% 
    left_join(
      data_ftsw_mean() %>% ungroup() %>% 
        filter(treatment=="stress") %>%
        select(genotype, time, FTSW)
    )
})

# analyse transpiration response as RER=f(FTSW)
data_response_transpiration <- reactive({
  data_rtr() %>% 
    left_join(data_ftsw_daily() %>% select(plant_code, time, FTSW))
})

# modeling transpiration response : regression on stressed:mean(contron) ~ FTSW
model_transpiration <- function(data) nls(rtr ~ curve_conductance(FTSW, a), data=data, start=list(a=-10), algorithm="default")

# filter dataset for relative ratio between in ]0, 1.5[
data_model_transpiration <- reactive({
  data_response_transpiration() %>% 
    filter(rtr < 1.5 & rtr > 0) %>% 
    group_by(genotype) %>% 
    nest() %>% 
    mutate(
      model=map(data, failwith(data.frame(NULL), model_transpiration)),
      prediction=map2(list_ftsw, model, failwith(data.frame(NULL), add_predictions)),
      coefficients=map(model, failwith(data.frame(NULL), tidy, quiet=TRUE)),
      rmse=map2(model, data, failwith(NULL, rmse))
    )
})


```

```{r data_computed_roots, include=FALSE}

# compute soil water capacity using a relative transpiration threshold as lower limit for soil transpirable water. 
data_awc <- reactive({
  data_rtr() %>% 
    filter(rtr > 0.05 & rtr <= 0.15) %>% 
    distinct(plant_code, .keep_all=TRUE) %>% 
    left_join(data_ftsw_daily() %>% select(plant_code, time, weight)) %>% 
    left_join(data_weight() %>% distinct(plant_code, weight_0)) %>% 
    mutate(
      TTSW = weight_0 - weight,
      awc = TTSW/weight_0
    )
})

data_awc_mean <- reactive({ data_awc() %>% ungroup() %>% summarise(sd=sd(awc), awc=mean(awc)) })

```


```{r data_computed_parameters, include=FALSE}

# gather estimated parameters
table_parameters <- reactive({
  bind_rows(
    left_join(
      data_model_expansion() %>% unnest(coefficients, .drop=TRUE) %>% mutate(process="LE"),
      data_model_expansion() %>% unnest(rmse, .drop=TRUE)
    ),
    left_join(
      data_model_transpiration() %>% unnest(coefficients, .drop=TRUE) %>% mutate(process="TR"),
      data_model_transpiration() %>% unnest(rmse, .drop=TRUE)
    ) 
  )
})

# summary table for modeling error 
table_error <- reactive({
  table_parameters() %>%
    group_by(process) %>% 
    summarise(
      n_genotype=n(),
      n_sign=sum(p.value < 0.01),
      n_low=sum(std.error < 2),
      estimate=mean(estimate, na.rm=TRUE),
      rmse=mean(rmse, na.rm=TRUE),
      se=mean(std.error, na.rm=TRUE)
    )
})
```


Sidebar {.sidebar}
=====================================

----------
### Selection

```{r inputs_design}

# shiny input for file selection (list)
# TODO : read existing dir
renderUI({
  selectInput('experiment', 'Experiment', list_experiment())
})
  
# shiny input for genotype selection (list)
renderUI({
  selectInput('genotype', 'Genotype', list_genotype())
})

# shiny input for interpolation (check)

```

----------
### Import

```{r inputs_import}
# import raw files

renderUI({
  actionLink("import", "Import (raw files)")  
})

table_import <- eventReactive(input$import, {
  soil_weight(experiment=input$experiment, index=data_index(), date_start=data_trial()$start)
})


# write processed raw files for analysis
renderUI({
  actionLink("write", "Write (weight)")  
})

observeEvent(input$write, {
  write_rds(table_import(), paste0("data/",input$experiment,"/",input$experiment,"_weight.rds"), compress="bz2")  
})


```

----------
### Harvest

```{r inputs_harvest}
# shiny input for planning date selection
renderUI({
  dateRangeInput('date', label='Dates', start=data_trial()$start, end=data_trial()$end)
})
  
# shiny input for filtering threshold
renderUI({
  sliderInput("threshold_ftsw", label="FTSW Threshold", min=0, max=1, value=0.1)
})


```

----------
### Model

```{r inputs_model}

# shiny input for ttsw estimation
renderUI({
  sliderInput("threshold_awc", label="Soil water capacity", min=0, max=1, value=0.61)
})

```


----------
### Export

```{r inputs_export}

# setup data download
output$table_download_area <- downloadHandler(
  file = paste0(input$experiment, "_", format(Sys.Date(), "%Y%m%d"),"_area.csv"), 
  content = function(file) {
    write_csv(write_heliaphen(table_harvest())$area, file, na="")
  }
)

renderUI({
  downloadLink('table_download_area', label = 'Download (leaf area)')  
})
  
output$table_download_architecture <- downloadHandler(
  file = paste0(input$experiment, "_", format(Sys.Date(), "%Y%m%d"),"_architecture.csv"), 
  content = function(file) {
    write_csv(write_heliaphen(table_harvest())$architecture, file, na="")
  }
)

renderUI({
  downloadLink('table_download_architecture', label = 'Download (architecture)')
})

```

----------

Design {data-orientation=rows}
=====================================  
    
Row {.data-height=150}
-------------------------------------
    
### Experimental design
```{r plot_design}
# plot experimental design
renderPlotly({
  ggplotly(
    data_index() %>%
      mutate(column=as.factor(column), line=as.factor(line)) %>%
      ggplot(aes(column, line, label=genotype)) +
      geom_tile(aes(fill=genotype), alpha=0.5) +
      geom_point(aes(shape=treatment), size=5, alpha=0.5) +
      scale_shape_manual(values=c(19, 1), guide = "none") +
      labs(x=NULL, y=NULL) + coord_equal() +
      theme(legend.position="none"),
    tooltip=c("x","y","label", "shape")
  )
})

```


Row {data-height=900}
-------------------------------------

### Table of harvestable plants
```{r table_harvest}

renderDataTable(
  table_harvest() %>%
    mutate(
      weight=round(weight, 0),
      FTSW=round(FTSW, 2),
      irrigation=round(irrigation, 0)
    ) %>%
    select(plant_code:irrigation, genotype, treatment),
  options=list(pageLength=10)
)

```


Import {data-orientation=rows}
=====================================  
```{r table_import}

renderDataTable(
  table_import(), options=list(pageLength=10)
)

```



Weight
=====================================     
   
Row  {.tabset}
-------------------------------------

### All genotypes
```{r plot_weight}

renderPlotly({
  ggplotly(
    data_weight() %>%
      ggplot(aes(x=time, y=weight, color=treatment, group=interaction(genotype, treatment), label=plant_code)) +
      geom_point(alpha=0.3) +
      geom_line(stat="smooth", method="loess", alpha=0.8, size=1) +
      geom_hline(aes(yintercept=0.1), linetype=2) +  
      scale_color_manual(values=c("#619CFF","#F8766D")) +
      scale_x_datetime(
        date_breaks="1 day", labels=date_format("%d", tz="Europe/Paris"),
        limits=c(data_trial()$start, data_trial()$end)
      ) + ylim(3500, 12000) +
      theme(legend.position="none"),
    tooltip=c("x","y","label")
  )
})

```


### Subset
```{r plot_weight_subset}

renderPlotly({
  ggplotly(
    data_weight() %>%
      filter(genotype == input$genotype) %>%
      ggplot(aes(x=time, y=weight, color=treatment, group=plant_code, label=plant_code)) +
      geom_line() +
      geom_hline(aes(yintercept=0.1), linetype=2) +
      scale_color_manual(values=c("#619CFF","#F8766D")) +
      scale_x_datetime(
        date_breaks="1 day", labels=date_format("%d", tz="Europe/Paris"),
        limits=c(data_trial()$start, data_trial()$end)
      ) + ylim(3500, 12000) +
      theme(legend.position="none"),
    tooltip=c("x","y","label")
  )
})

```




Water deficit
=====================================     
   
Row  {.tabset}
-------------------------------------

### All genotypes
```{r plot_stress}

renderPlotly({
  ggplotly(
    data_ftsw() %>%
      ggplot(aes(x=time, y=FTSW, color=treatment, group=interaction(genotype, treatment), label=plant_code)) +
      geom_point(alpha=0.3) +
      geom_line(stat="smooth", method="loess", alpha=0.8, size=1) +
      geom_hline(aes(yintercept=input$threshold_ftsw), linetype=2) +  
      scale_color_manual(values=c("#619CFF","#F8766D")) +
      scale_x_datetime(
        date_breaks="1 day", labels=date_format("%d", tz="Europe/Paris"),
        limits=c(data_trial()$start, data_trial()$end)
      ) + ylim(0, 1.2) +
      theme(legend.position="none"),
    tooltip=c("x","y","label")
  )
})

```


### Subset
```{r plot_stress_subset}

renderPlotly({
  ggplotly(
    data_ftsw() %>%
      filter(genotype == input$genotype) %>%
      ggplot(aes(x=time, y=FTSW, color=treatment, group=plant_code, label=plant_code)) +
      geom_line() +
      geom_hline(aes(yintercept=input$threshold_ftsw), linetype=2) +
      scale_color_manual(values=c("#619CFF","#F8766D")) +
      scale_x_datetime(
        date_breaks="1 day", labels=date_format("%d", tz="Europe/Paris"),
        limits=c(data_trial()$start, data_trial()$end)
      ) + ylim(0, 1.2) +
      theme(legend.position="none"),
    tooltip=c("x","y","label")
  )
})

```


### Interpolation
```{r plot_stress_interpolation}

renderPlotly({
  ggplotly(
    data_ftsw_daily() %>%
      filter(genotype == input$genotype) %>%
      ggplot(aes(x=time, y=FTSW, color=treatment, group=plant_code, label=plant_code)) +
      geom_line() +
      geom_hline(aes(yintercept=input$threshold_ftsw), linetype=2) +
      scale_color_manual(values=c("#619CFF","#F8766D")) +
      scale_x_datetime(
        date_breaks="1 day", labels=date_format("%d", tz="Europe/Paris"),
        limits=c(data_trial()$start, data_trial()$end)
      ) + ylim(0, 1.2) +
      theme(legend.position="none"),
    tooltip=c("x","y","label")
  )
})

```

### Data
```{r table_harvest_planning}

# TODO : add filter for selected dates 
renderDataTable(
  data_ftsw() %>%
    filter(
      time >= ymd(as.character(input$date[1]), tz="Europe/Paris"),
      time < ymd(as.character(input$date[2]), tz="Europe/Paris")
      ) %>%
    select(plant_code:irrigation, genotype, treatment),
  options=list(pageLength=10)
)

```


Leaf area
=====================================     

Row  {.tabset}
-------------------------------------

### Leaf profile
```{r plot_leaf_profile}

renderPlotly({
  ggplotly(
    data_area() %>% 
      filter(genotype %in% input$genotype) %>% 
      mutate(time=as.character(time), area=area/100) %>% 
      ggplot(aes(x=area, y=leaf, color=time, group=time, label=time)) +
      geom_path() +
      geom_point(
        data=data_area_raw() %>%
          filter(genotype %in% input$genotype) %>%
          mutate(
            time=as.character(time),
            area=area/100, leaf=as.integer(leaf)
          ), size=1
      ) +
      facet_wrap(~ treatment + plant_code, ncol=6) +
      coord_cartesian(xlim=lim_area) +
      scale_color_viridis(discrete=TRUE, option="plasma", end=0.95) +
      labs(x="Leaf area (cm2)", y="Node") + theme(legend.position="none"),
    tooltip=c("x","y","label")
  )
})



```

### Leaf dynamics
```{r plot_leaf_dynamics}

renderPlotly({
  ggplotly(
    data_area() %>% 
      filter(genotype %in% input$genotype) %>% 
      mutate(area=area/100) %>% 
      ggplot(aes(x=time, y=area, color=leaf, group=leaf, label=leaf)) +
      geom_path() +
      geom_point(
        data=data_area_raw() %>%
          filter(genotype %in% input$genotype) %>% 
          mutate(area=area/100), size=1
      ) + 
      facet_wrap(~ treatment + plant_code, ncol=6) +
      coord_cartesian(ylim=lim_area) +
      scale_color_viridis(option="plasma", end=0.95) +
      scale_x_datetime(
        date_breaks="2 day", labels=date_format("%d", tz="Europe/Paris")
      ) +
      labs(x="Time", y="Leaf area (cm2)") + theme(legend.position="none"),
    tooltip=c("x","y","label")
  )
})

```

### Plant dynamics
```{r plot_plant_dynamics}

renderPlotly({
  ggplotly(
    data_plant() %>%
      filter(genotype == input$genotype) %>%
      gather(method, area, area:area_active) %>% 
      mutate(area=area/1e6) %>% 
      ggplot(aes(x=time, y=area, color=treatment, label=plant_code)) +
      geom_point(data=. %>% filter(method=="area"), alpha=0.5) +
      geom_smooth(aes(linetype=method), method="loess", se=FALSE) +
      scale_treatment +
      labs(y="Plant area (m2)") +
      scale_x_datetime(
        date_breaks="1 day", labels=date_format("%d", tz="Europe/Paris"),
        limits=c(data_trial()$start, data_trial()$end)
      ) + 
      theme(legend.position="none"),
    tooltip=c("x","y","label")
  )
})


```



Expansion
=====================================     

Row  {.tabset}
-------------------------------------

### Rate
```{r plot_expansion_rate}
renderPlotly({
  ggplotly(
    data_expansion() %>%
      filter(genotype == input$genotype) %>%
      ggplot(aes(x=time, y=d_area, color=treatment)) +
      geom_point(data=data_expansion_mean() %>% filter(genotype == input$genotype), size=2) +
      geom_point(aes(label=plant_code), size=1, alpha=0.5) +
      geom_smooth(method="loess", se=FALSE) +
      scale_treatment +
      scale_x_datetime(
        date_breaks="1 day", labels=date_format("%d", tz="Europe/Paris"),
        limits=c(data_trial()$start, data_trial()$end)
      ) + 
      labs(y="Mean expansion rate (mm2.d-1)") +
      theme(legend.position="none")
  )
})

```


### Relative
```{r plot_expansion_relative}
renderPlotly({
  ggplotly(
    data_rer() %>% 
      filter(genotype == input$genotype) %>%
      ggplot(aes(time, rer, label=plant_code)) +
      geom_point(alpha=0.5) +
      geom_smooth() +
      scale_x_datetime(
        date_breaks="1 day", labels=date_format("%d", tz="Europe/Paris"),
        limits=c(data_trial()$start, data_trial()$end)
      ) +
      labs(y="Relative expansion rate") 
  )
})

```


### Model
```{r plot_expansion_model}
renderPlotly({
  ggplotly(
    data_response_expansion() %>%
      filter(genotype == input$genotype) %>%
      ggplot(aes(x=FTSW, y=rer)) +
      geom_point(aes(label=plant_code), alpha=0.3, size=1) +
      geom_point(
        data=data_response_expansion_mean() %>%
          filter(genotype == input$genotype),
        size=2) +
      geom_line(
        data=data_model_expansion() %>%
          filter(genotype == input$genotype) %>% 
          unnest(prediction),
        aes(x=FTSW, y=pred), color="#619CFF", size=1
      ) +
      coord_cartesian(xlim=c(0,1), ylim=c(0,1.5)) +
      labs(y="Relative Expansion Rate")
  )
})
```

### Quality
```{r plot_expansion_model_quality}
renderPlotly({
  ggplotly(
    data_model_expansion() %>%
      unnest(coefficients, .drop=TRUE) %>% 
      ggplot(aes(x=reorder(genotype, p.value), y=p.value)) +
      geom_point() + geom_hline(yintercept = 0.05) + 
       labs(x=NULL, y="p-value")
  )
})
```



Transpiration
=====================================     

Row  {.tabset}
-------------------------------------

### Rate
```{r plot_transpiration_rate}
renderPlotly({
  ggplotly(
    data_transpiration() %>% 
      filter(genotype == input$genotype) %>%
      ggplot(aes(x=time, y=tr*100, color=treatment)) +
      geom_point(data=data_transpiration_mean() %>% filter(genotype == input$genotype), size=2) +
      geom_point(aes(label=plant_code), size=1, alpha=0.5) +
      geom_smooth(method="loess", se=FALSE) +
      scale_treatment +
      scale_x_datetime(
        date_breaks="1 day", labels=date_format("%d", tz="Europe/Paris"),
        limits=c(data_trial()$start, data_trial()$end)
      ) +
      labs(y="Transpiration rate (g.cm-2.d-1)") +
      theme(legend.position="none")
  )
})
```

### Relative
```{r plot_transpiration_relative}
renderPlotly({
  ggplotly(
    data_rtr() %>% 
      filter(genotype == input$genotype) %>%
      ggplot(aes(time, rtr, label=plant_code)) +
      geom_point(alpha=0.5) +
      geom_smooth(data= . %>% filter(rtr < 1.5 & rtr > 0)) +
      coord_cartesian(ylim=c(0,1.5)) +
      scale_x_datetime(
        date_breaks="1 day", labels=date_format("%d", tz="Europe/Paris"),
        limits=c(data_trial()$start, data_trial()$end)
      ) +
      labs(y="Relative transpiration rate") 
  )
})
```

### Model

```{r plot_transpiration_model}
renderPlotly({
  ggplotly(
    data_response_transpiration() %>%
      filter(genotype == input$genotype) %>%
      ggplot(aes(x=FTSW, y=rtr)) +
      geom_point(aes(label=plant_code), alpha=0.3, size=1) +
      geom_point(
        data=data_response_transpiration_mean() %>%
          filter(genotype == input$genotype),
        size=2) +
      geom_line(
        data=data_model_transpiration() %>%
          filter(genotype == input$genotype) %>% 
          unnest(prediction),
        aes(x=FTSW, y=pred), color="#619CFF", size=1
      ) +
      coord_cartesian(xlim=c(0,1), ylim=c(0,1.5)) +
      labs(y="Relative Transpiration Rate")
  )
})
```

### Quality
```{r plot_transpiration_model_quality}
renderPlotly({
  ggplotly(
    data_model_transpiration() %>%
      unnest(coefficients, .drop=TRUE) %>% 
      ggplot(aes(x=reorder(genotype, p.value), y=p.value)) +
      geom_point() + geom_hline(yintercept = 0.05) + 
       labs(x=NULL, y="p-value")
  )
})
```



Roots
=====================================     

Row  {.tabset}
-------------------------------------

### Extraction
```{r plot_root_extraction}
renderPlotly({
  ggplotly(
    data_awc() %>% 
      mutate(awc=awc*100) %>% 
      ggplot(aes(x=genotype, y=awc, label=plant_code)) +
      geom_point(alpha=0.5) + 
      geom_hline(aes(yintercept=data_awc_mean()$awc*100)) +
      labs(x=NULL, y="Available soil water (%)") 
  )
})
```



Data
=====================================     

Row  {.tabset}
-------------------------------------


### Parameters
```{r table_response}

renderDataTable(
  table_parameters() %>% 
    select(process, genotype, estimate, se=std.error, p.value, rmse) %>% 
    arrange(process, -estimate),
  options=list(pageLength=20)
)

```

### Quality
```{r table_error}

renderDataTable(
  table_error() 
)

```

